enum PaymentSSEEventType {
  PAYMENT_INITIAL_LIST = 'PAYMENT_INITIAL_LIST',
  PAYMENT_UPDATED = 'PAYMENT_UPDATED',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  HEARTBEAT = 'HEARTBEAT',
  CONNECTED = 'CONNECTED',
  ERROR = 'ERROR',
  KYC_STATUS = 'KYC_STATUS',
}

enum PaymentType {
  COMPLETED = 'COMPLETED',
  PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED',
  FULLY_REFUNDED = 'FULLY_REFUNDED',
}

export { PaymentSSEEventType, PaymentType };
